 **1**

In [ ]:
# < START >
import numpy as np
arr=np.array([[1,2,3],[23,311,32]])
# < END >

print(arr)
print("Shape:", arr.shape)

[[  1   2   3]
 [ 23 311  32]]
Shape: (2, 3)


**2**

In [ ]:
n_rows = 2
n_columns = 3

#
x=np.random.random(size=(n_rows,n_columns))
## or x=np.random.randn(n_rows,n_columns)
#

print(x)


[[0.216225   0.28005671 0.78723644]
 [0.30826678 0.34751791 0.12613515]]


**3**

In [ ]:
# < START >
# Initialize an array ZERO_ARR of dimensions (4, 5, 2) whose every element is 0
import numpy as np
ZERO_ARR=np.zeros((4,5,2))


# < END >

print(ZERO_ARR)

# < START >
# Initialize an array ONE_ARR of dimensions (4, 5, 2) whose every element is 1
ONE_ARR=np.ones((4,5,2))
# < END >

print(ONE_ARR)


[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


**4**

In [21]:
y = np.array([[1, 2, 3],
              [4, 5, 6]])

# < START >
# Create a new array y_transpose that is the transpose of matrix y
y_transpose=y.T # to transpose a matrix
# < END >

print(y_transpose)

# < START >
# Create a new array y_flat that contains the same elements as y but has been flattened to a column array
y_flat=y.flatten()
y_flat=y_flat.reshape(-1,1) # or reshape(6,1)
#print(y_flat)
# y.flatten() converts it into a row array


# < END >

print(y_flat)

[[1 4]
 [2 5]
 [3 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


**5**

In [14]:
#
import numpy as np
# Initialize the column matrix here
y=np.array([4,7,11])
y=y.reshape(3,1)
#

assert y.shape == (3, 1)
# The above line is an assert statement, which halts the program if the given condition evaluates to False.
# Assert statements are frequently used in neural network programs to ensure our matrices are of the right dimensions.

print(y)

#
x=np.array([[1,2,3],[4,5,6]])
#x=np.random.random(size=(2,3))
print(x)
# Multiply both the arrays here
print(np.dot(x,y))
#
z=np.array([[1],[3]])
assert z.shape == (2, 1)
print(z)

[[ 4]
 [ 7]
 [11]]
[[1 2 3]
 [4 5 6]]
[[ 51]
 [117]]
[[1]
 [3]]


**6**

In [ ]:
x = np.array([4, 1, 5, 6, 11])

#
# Create a new array y with the middle 3 elements of x
y=x[1:4]

#

print(y)

z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

#
# Create a new array w with alternating elements of z
w=z[::2]
#

print(w)

[1 5 6]
[1 3 5 7 9]


**7**

In [ ]:
arr_2d = np.array([[4, 5, 2],
          [3, 7, 9],
          [1, 4, 5],
          [6, 6, 1]])

#
# Create a 2D array sliced_arr_2d that is of the form [[5, 2], [7, 9], [4, 5]]
sliced_arr_2d=arr_2d[0:3,1:]
#

print(sliced_arr_2d)

[[5 2]
 [7 9]
 [4 5]]


**8**

In [9]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
b = 1

#
# Implement broadcasting to add b to each element of arr1
arr1=arr1+b
#

print(arr1)

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr3 = np.array([[4],
                 [5]])

#
# Multiply each element of the first row of arr2 by 4 and each element of the second row by 5, using only arr2 and arr3
arr2=arr2 * arr3 # for element wise multiplication arr2 and arr3 should be same size like [[4,4,4],[5,5,5]]

print(arr2)

[2 3 4 5]
[[ 4  8 12]
 [20 25 30]]


**9**

In [20]:
import time
import numpy as np
arr_nonvectorized = np.random.rand(1000, 1000)
arr_vectorized = np.array(arr_nonvectorized) # making a deep copy of the array

start_nv = time.time()

# Non-vectorized approach
#
for i in range(arr_nonvectorized.shape[0]):
  for j in range(arr_nonvectorized.shape[1]):
    arr_nonvectorized[i,j]= arr_nonvectorized[i,j]*3

#

end_nv = time.time()
print("Time taken in non-vectorized approach:", 1000*(end_nv-start_nv), "ms")

# uncomment and execute the below line to convince yourself that both approaches are doing the same thing
print(arr_nonvectorized)
start_v = time.time()

# Vectorized approach
#
arr_vectorized=arr_vectorized*3
#

end_v = time.time()
print("Time taken in vectorized approach:", 1000*(end_v-start_v), "ms")

# uncomment and execute the below line to convince yourself that both approaches are doing the same thing
print(arr_vectorized)

Time taken in non-vectorized approach: 502.1343231201172 ms
[[0.05608324 0.48848895 1.22644149 ... 0.33950259 2.46709877 0.50186353]
 [1.13289314 1.43310162 1.93772675 ... 1.10714143 0.0859515  0.56114607]
 [0.98742137 1.84557007 2.51424939 ... 2.50312021 2.49745327 0.37126046]
 ...
 [2.37886602 0.89558179 2.39756066 ... 0.58560845 0.11081364 1.01763414]
 [1.49570039 1.37285205 1.87487295 ... 2.77688208 0.23767604 0.6030684 ]
 [1.64951869 0.65742334 2.00045331 ... 2.6853612  0.28534314 2.16049261]]
Time taken in vectorized approach: 2.3550987243652344 ms
[[0.05608324 0.48848895 1.22644149 ... 0.33950259 2.46709877 0.50186353]
 [1.13289314 1.43310162 1.93772675 ... 1.10714143 0.0859515  0.56114607]
 [0.98742137 1.84557007 2.51424939 ... 2.50312021 2.49745327 0.37126046]
 ...
 [2.37886602 0.89558179 2.39756066 ... 0.58560845 0.11081364 1.01763414]
 [1.49570039 1.37285205 1.87487295 ... 2.77688208 0.23767604 0.6030684 ]
 [1.64951869 0.65742334 2.00045331 ... 2.6853612  0.28534314 2.160492